version: '2'
services:
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROP_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CREATE_TOPICS: "topic_1:1:1,topic_2:10:1:compact"
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-single
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
