version: '2'
services:
  kafka-broker-1:
    image: tidexenso/kafka-kraft:latest
    ports:
      - "19092:9092"
    environment:
      KAFKA_CLUSTER_ID: aktrcaTSRsmKDFqALt0KLA
      KAFKA_PROP_NODE_ID: 1
      KAFKA_PROP_PROCESS_ROLES: "broker,controller"
      KAFKA_PROP_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:9093"
      KAFKA_PROP_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_PROP_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-1:9092"
      
      KAFKA_CREATE_TOPICS: "topic_1:1:1,topic_2:10:2:compact"
    restart: unless-stopped

  kafka-broker-2:
    image: tidexenso/kafka-kraft:latest
    ports:
      - "29092:9092"
    environment:
      KAFKA_CLUSTER_ID: aktrcaTSRsmKDFqALt0KLA
      KAFKA_PROP_NODE_ID: 2
      KAFKA_PROP_PROCESS_ROLES: "broker"
      KAFKA_PROP_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:9093"
      KAFKA_PROP_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_PROP_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-2:9092"
    restart: unless-stopped

  kafka-broker-3:
    image: tidexenso/kafka-kraft:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "39092:9092"
    environment:
      KAFKA_CLUSTER_ID: aktrcaTSRsmKDFqALt0KLA
      KAFKA_PROP_NODE_ID: 3
      KAFKA_PROP_PROCESS_ROLES: "broker"
      KAFKA_PROP_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:9093"
      KAFKA_PROP_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_PROP_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-3:9092"
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-multi
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-2:9092
