apiVersion: v1
kind: Service
metadata:
  name: kafka-serv
spec:
  selector:
    wams.service: kafka
  type: NodePort
  ports:
    - name: internal
      port: 9092
    - name: external
      port: 9093
    - name: nodeport
      port: 30092
      nodePort: 30092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      wams.service: kafka
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        wams.service: kafka
    spec:
      containers:
        - name: kafka
          image: kafka-kraft
          imagePullPolicy: IfNotPresent
          resources: {}
          securityContext:
            privileged: false
          env:
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,NODEPORT:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092,EXTERNAL://:9093,NODEPORT://:30092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://localhost:9092,EXTERNAL://kafka-serv:9093,NODEPORT://localhost:30092"
            - name: KAFKA_CREATE_TOPICS
              value: "object-models,timeseries,calculations,functions"
          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 9093
              name: external
            - containerPort: 30092
              name: nodeport
